version: '3.7'
services:
  app:
    image: app
    build: .
    ports:
      - target: 5000
        published: 80
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=flask_database
    volumes:
      - datavolume:/var/lib/mysql
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - target: 8080
        published: 8080
volumes:
  datavolume: {}
